### ISSUE TITLE
Background margin/padding

### ISSUE THREAD

**Issue by Paulinelali** [Arsenethierry/my-portifolio-microverse#5]
I think the background margin/padding should be removed so that it will take the full width of the view port.

**Comment by olanikegloria** [comment]
I think setting the background size to cover would let it take the full width of the view port

**Comment by lily4178993** [comment]
It should be easy to start with the [mobile version first](https://www.webucator.com/mobile-training/mobile-web-development.cfm).

**Comment by Paulinelali** [comment]
Thank you all for your contributions
Do have happy coding day😎
