### ISSUE TITLE
Portifolio deployment

### ISSUE THREAD

**Issue by Arsenethierry** [Arsenethierry/my-portifolio-microverse#9]
[This demo link](https://arsenethierry.github.io/my-portifolio-microverse/) redirects to my deployed portifolio, I deployed it before I get to deployment task that's why I am opening this issue insteed of pull request.

**Comment by taldr27** [comment]
# Status: Approved! 🟢 
Hi @Arsenethierry, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉

![congrats](https://media.giphy.com/media/3oEjI5VtIhHvK37WYo/giphy.gif)

## Highlights 🎉
✅ README includes a working live link. 🤓
✅ Successfully deployed using GitHub Pages. 👍
✅ Live page is fully functional. 🎯

-----
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @taldr27 in your question so I can receive the notification.

If you need any further help or have any questions, feel free to reach out to me on Slack as _**Diego Garcia**_.🎯

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s). <img align="right" src="https://media.giphy.com/media/kReKcfrs1YoTmt2AQt/giphy.gif" alt="gif"  width="3%"/>_
